### ISSUE TITLE
Seting up APNs Message priority using pushsharp

### ISSUE THREAD

**Issue by shroffpratik** [Redth/PushSharp#476]
How to setup message prioroty for APNs for push notification? In APNs documentation we have message prioroty values 10 or 5. how to implement this using push sharp?

**Comment by shroffpratik** [comment]
I have tried updating pushsharp with new format but Calling APNS with New format does not send the message. When you planning to update the pushsharp library with new format?  Is there any suggested code available. I need urgent help in this issue.

**Comment by hooflak** [comment]
Hi,
Any update on this - it still looks like the priority from PushSharp messages is defaulting to 5 rather then 10?  Is anybody seeing similar behaviour?  We have messages not showing up when the receivers device is low on battery.

**Comment by alaa9jo** [comment]
@Redth didn't make any updates on the library,and unfortunately with the heavy workload I still have with other projects I didn't make any progress on this feature

As for your issue,PushSharp definitely not passing `priority` since it still uses the legacy format __[Enhanced Notification Format](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html)__ , and clearly as Apple stated at the head of the document:
> These formats do not include a priority; a priority of 10 is assumed.
