### ISSUE TITLE
PushSharp Service Errors while pushing To Apple

### ISSUE THREAD

**Issue by JaneZhang2011** [Redth/PushSharp#496]
I had two errors while using PushSharp with C#, even I didn't change my codes, everytime I run my program, the error may be changed, and no any rules. The certificates I use is .p12
One error is "Authentication failed because the remote party has closed the transport stream " and the other one is "A call to SSPI failed, see inner exception." and the inner exception is "The message received was unexpected or badly formatted"
I had try to change SslProtocols from Ssl3 to Tls in ApplePushChannel.cs, and it doesn't for me.

**Comment by alaa9jo** [comment]
"A call to SSPI failed" is usually reported when the certificate file you're using is expired/revoked

"Authentication failed because the remote party has closed the transport stream" is usually reported either for the same reason as above

How to fix it:
You have to access Apple developer console,double check on the certificate from there,if it's expired you have to generate a new one,download it and use it in your app , if not then you have to download the certificate anyway and use it in your app,because most likely it was revoked in the past and you're looking at the new generated one,different from the one you're using in your app

**Comment by JaneZhang2011** [comment]
Ok I 'll try it again.Thank you very much.But I still have a question,The certificate I download from Apple developer console is .pem and I have to transform it to .p12, right?It's there any possible that the certificate was damaged when I transform them?

**Comment by alaa9jo** [comment]
Please follow the steps in the following link on how to download production SSL certificate:
http://quickblox.com/developers/How_to_create_APNS_certificates#Make_APNS_certificates

**Comment by JaneZhang2011** [comment]
Now, I can sure there is nothing wrong with my certificate, because in java programe I can push message to my phone with the same certificate, but in C# I still got the same two errors

**Comment by alaa9jo** [comment]
Strange,I faced those two issues you mentioned and the fix for me was to get the latest certificate as I mentioned earlier.

If you're using the latest update of PushSharp and with the same certificate you still get these errors then it must be something wrong with your code of how you're using the library

Have you tried to use the latest update of PushSharp ? Are you following the examples provided with the library? Are there a steps to reproduce the issue?

**Comment by 4311021x** [comment]
I've seen a System.IO.IOException exception with the message "Authentication failed because the remote party has closed the transport stream" before. It occurs when the remote party doesn't accept your System.Security.Authentication.SslProtocols which causes the remote party to disconnect during authentication. So if you require TLS but the remote party requires TLS1.2, it leads to this exception.

**Comment by alaa9jo** [comment]
PushSharp was updated last year to use `SslProtocols.Tls` instead of  `SslProtocols.Ssl3` after [Apple's update](https://developer.apple.com/news/?id=10222014a) ,these error messages he's facing were fixed long time ago in the latest update,that's why I asked if he's using the latest version and if his code is correct,if he can post his code that may help
