### ISSUE TITLE
APNS failing to deliver more than 11 messages to a single device at one go

### ISSUE THREAD

**Issue by ManishGoenka** [Redth/PushSharp#500]
I am having a problem when trying to send more than 11 unique notifications through APNS. 
I am using PushSharp version 2.2.1.0 with .Net framework 4.5. On debugging the code I still get the NotificationSent event for all the notifications i.e. say 20 messages. On further investigation I found that if I introduced a delay of 10 seconds while queuing the message using the QueueNotification method then all the messages come through to the device.

Has anyone noticed this?

**Comment by alaa9jo** [comment]
There is a known limitation from Apple,look [here]("https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG23") , this could be your case

I'm using the library but I've never sent many notifications to same device in one go,for a lot of reasons; either I didn't have to or the limitation I told you earlier or I didn't want Apple to revoke my apps certificates because of misuse/overburden their services which I read it somewhere in their docs

Maybe you should delay your queue a little bit,10 seconds is way too much,maybe you should start with 10 millisecond,then start increasing that number i.e. 10,100,250,500..etc till you reach a number that worked for you,yes it's a try-and-error thing,I can't think of a better way

Let me know about your results :)

**Comment by ManishGoenka** [comment]
Hi alaa9jo, thanks for your response - Introducing delay in ms did not help the cause, also 2 - 3 seconds did not have any different effect. I have coded around to not send more than 10 messages to a single device, if it ever happens to be the case. Thanks once again.
