### ISSUE TITLE
Client Authentication Error - Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by rajumvn** [Redth/PushSharp#507]
Hi Redth/Team,

We have been facing an issue while sending push notifications to APNS. 

This seems to be strange and happening with our client network only. Some times push notifications are successfully sent to APNS and in other attempts it fails with error "The maximum number of Send attempts to send the notification was reached! ".

To identify the actual issue running inside and why its attempting multiple times to connect APNS, we have implemented custom logs and found that its failing because of following exception.

Actual Error: "Authentication failed because the remote party has closed the transport stream.".

This is only happening in our client network but in our organization and my home network the application work pretty good and quick. 

In our client network, the required ports (2195, 2196) are opened and allowed any address in the Apple range (17.0.0.0/8). Also, following telnet statement are executed and connected APNS servers. The code base already tried with following two options as well.

Option#1:
stream.AuthenticateAsClient(settings.FeedbackHost, certificates, System.Security.Authentication.SslProtocols.Default, false);

Options#2:
stream.AuthenticateAsClient(settings.FeedbackHost, certificates,
                    System.Security.Authentication.SslProtocols.Ssl3 | System.Security.Authentication.SslProtocols.Tls, false);

telnet gateway.push.apple.com 2195
telnet gateway.sandbox.push.apple.com 2195

telnet feedback.sandbox.push.apple.com 2196
telnet feedback.push.apple.com 2196

Some of the times, notifications are sent successfully to APNS and other times they get failed. Its a mixed results always.

Request you, kindly review this exception case and let us know your suggestions and if you have find any resolutions. I am in a critical phase of completing the push notification requirements and deliver the project to client priority needs.

Sincere apologies for creating the duplicate issue ticket for the same issue (Authentication failed because the remote party has closed the transport stream.). I had referenced previous post on the same issue but couldn't find any working solution or resolution.

Hope you can understand my case and extend your help.

Thanks,
Raju MVN

**Comment by rajumvn** [comment]
Can this be related to an issue with Windows 2003 Server since it is old and not able to understand TLS? Please refer the following URL and reference from Microsoft.

http://blogs.msdn.com/b/jpsanders/archive/2009/01/07/you-receive-one-or-more-error-messages-when-you-try-to-make-an-http-request-in-an-application-that-is-built-on-the-net-framework-2-0.aspx

**Comment by Fleskarn** [comment]
I have the same problem.

Program I built using Push Sharp _sometimes_ works. Sometimes it just gets the error when the pushbrokers gets initiated.

A first chance exception of type 'System.IO.IOException' occurred in System.dll
Service Exception: PushSharp.Apple.ApplePushService -> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.

**Comment by oliverjanik** [comment]
Same problem here, started happening recently.

**Comment by markeins** [comment]
Same problem here... I'm using MoonAPNS library... Windows 2012 server and also tested on Windows 8.1.

**Comment by mutharasank** [comment]
Hi i am also getting Same problem here,Windows 2012 server and windows 8.1

**Comment by saiabbena** [comment]
Please make sure you have SSL installed on the server and also make sure 2195 port number is opened.

**Comment by tamarzil** [comment]
I have the same problem on Windows 2012 server. It happens sporadically, most times notifications are sent just fine, but every now and then an entire bulk of notifications fails - each with the above exception.
This often happens at times when we're sending multiple bulks of notifications at the same time (from multiple threads and multiple machines). 
Can it be Apple blocking the connection due to rapid opening and closing of channels? Our implementation is not ideal when it comes to channel creation and destruction, and I know that Apple can consider it as a denial-of-service attack and block connections for a period of time:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW6

**Comment by AtlasRider** [comment]
I am also having this issue. Same code runs on my Windows 8 machine, but fails more often than not on my Windows 2008 Server

**Comment by martintw63** [comment]
We are running 2.2.1 and get our updates via NuGet.  We are having the same issues.  "Authentication failed because the remote party has closed the transport stream." and "The maximum number of Send attempts to send the notification was reached!"  These issues started on October 16th (mainly the Authentication failure).  Is this error in relation to the new IOS update?  I've tried re-setting the SecurityProtocolType.  

Any help would be appreciated.

Thank you,

**Comment by Fleskarn** [comment]
I had this issue previously, and found out that after manually installing the push-certificates on my pcs it all worked fine.. (Windows 10, Windows 7 and Windows 8). Found nowhere it was said that should be required but it seemed it was the case..

**Comment by Hoshinokoe** [comment]
I had the same issue. Ports are open, certificate is valid.
Does anybody have solution to solve this ?

**Comment by Fleskarn** [comment]
Hoshinokoe, if you are under Windows, try manually install each certificate on the local machine before running your program. (Double click them in explorer)

It fixed the issue for me (and Ive not seen it mentioned anywhere..)

Skickat från min iPhone

**Comment by Hoshinokoe** [comment]
It works on my Windows 10 machine, but doesn't work on Windows Server 2012. 
Configuration are the same. Can anyone help ?

**Comment by Fleskarn** [comment]
Hoshinokoe did you try manually install the certificates on the Windows
Server 2012 machine?

Do you run your program as administrator?

Best
A

On Tue, Dec 29, 2015 at 4:43 PM, Hoshinokoe <notifications@github.com>
wrote:

> It works on my Windows 10 machine, but doesn't work on Windows Server
> 2012.
> Configuration are the same. Can anyone help ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Redth/PushSharp/issues/507#issuecomment-167815862>.
>



-- 
-- 
Anton Westbergh
anton.westbergh@coffeestainstudios.com
CEO - Coffee Stain Studios
+46(0)723019121

**Comment by Thordax** [comment]
For me, the problem was that I had an old production certificate installed on my Windows certificate store (certmgr.msc). Deleting it, and adding the new certificate solved my problem.
