### ISSUE TITLE
Push Not recieved on Android !! 

### ISSUE THREAD

**Issue by propertynoticed** [Redth/PushSharp#539]
Hi,
I am using PushPlugin on my android device. I have configured following settings and able to generate registration ID for my app and saving it to database on server.
On Device)
1) Application Package Name - OK 
2) Sender ID which is Project Number - OK
3) Device ID Received from GCM - OK 

On Server : 
API - Server Key Added - OK
When i send push message using Device ID I get following  log message : 

"Channel Created for: PushSharp.Android.GcmPushService"

That's it No Success message or Push Message on Device. 

Using Latest version of Push Sharp.

Please help.

Thanks A Lot in Advance

Kunal Deshmukh

**Comment by roman-yagodin** [comment]
It may take some time - in my case it is generally 5-30 min before receiving notification on device. Note what there is "official" utility to test GCM, see: https://github.com/google/gcm/tree/master/samples/android/gcm-demo.

**Comment by kcd83** [comment]
Make sure you at least implement the these two handlers to see happened
```csharp
_PushBroker.OnNotificationFailed += NotificationFailedHandler;
_PushBroker.OnNotificationSent += NotificationSentHandler;

static void NotificationSentHandler(object sender, INotification notification)
{
	// log it
}

static void NotificationFailedHandler(object sender, INotification notification, Exception exception)
{
	// log it
}
```

**Comment by denstorti** [comment]
Maybe it's not a Pushsharp error, as @roman-yagodin said, it may take some minutes until the push arrives on device, probably due to the heartbeat problem. (detailed in this link http://eladnava.com/google-cloud-messaging-extremely-unreliable/).

Default configuration for Google Play Services is 28 minutes on mobile data connection or 4 minutes on Wifi connection. You can see it typing *#*#426#*#* on your android device.
