### ISSUE TITLE
Hangs on build

### ISSUE THREAD

**Issue by super-coder** [Redth/PushSharp#579]
I have a i7 and 12 Gb of memory and every time I build the solution it hangs for few minutes 

![image](https://cloud.githubusercontent.com/assets/2155554/11623900/f1e57ee8-9d0a-11e5-91d8-41fc95eec759.png)

**Comment by super-coder** [comment]
sure just close them bugs, no point waste time checking out

**Comment by Redth** [comment]
Sorry for the confusion. Version 3.x is a complete rewrite and the only way for me to sanely manage this free and open source project going forward was to close the 2.x related issues since they don't really make sense with respect to the new code base. Please feel free to open a new issue if you are experiencing the same issue with v3.x.

**Comment by super-coder** [comment]
OK, thanks a ton
