### ISSUE TITLE
New apple certificates.

### ISSUE THREAD

**Issue by v-tsymbalistyi** [Redth/PushSharp#585]
PushSharp does not recognize new Apple production certificates created after this update:
https://developer.apple.com/news/?id=12172015b

Error text:Service cannot be started. System.ArgumentException: You have selected the Production server, yet your Certificate does not appear to be the Production certificate!  Please check to ensure you have the correct certificate!

**Comment by v-tsymbalistyi** [comment]
You are checking for "Apple Production IOS Push Services" and it is "Apple Push Services" now.

**Comment by v-tsymbalistyi** [comment]
Created pull request with potential fix.
I think you should find a better way to validate certificate type though.

**Comment by perlasivakrishna** [comment]
Mine also Same problem How to get rid of this ?

**Comment by Redth** [comment]
If you're on the 2.x version of PushSharp you can disable the certificate check (apple changed the name in the certificate generated), use a constructor that allows you to disable the certificate check and explicitly set the production flag:
https://github.com/Redth/PushSharp/blob/master/PushSharp.Apple/ApplePushChannelSettings.cs#L50

On the 3.x branch there's similar ctor's:
https://github.com/Redth/PushSharp/blob/3.0-dev/PushSharp.Apple/ApnsConfiguration.cs#L61

Eventually I will fix this on 3.x (basically we'll just have a flag for production and not care about certificate checks since there's only one cert now going forward), but for now that is the work around.

**Comment by perlasivakrishna** [comment]
I am using only reference files (.dll), so i am not able to change any thing through our project. currently i am using PushSharp 2.2.1 version. how can i solve this problem with new certificates. Please help me.
Thanks in advance.

**Comment by v-tsymbalistyi** [comment]
perlasivakrishna, take a look on ApplePushChannelSettings constructors. It has boolean parameter to disable certificate check.

**Comment by perlasivakrishna** [comment]
v-tsymbalistyi, thanks for your reply. As per your comment i am not able to change any thing through my project even i try to remove bool request in ApplePushChannelSettings constructor. I think i get this constructor through pushsharp.dll file. that's why i can't do any thing in this file. Can i add any new reference files or Is any way to change that code.

**Comment by hemang-azilen** [comment]
@Redth , even after setting in 2.x version of PushSharp, I am not getting any push notification from my server..same thing working fine with development.

**Comment by v-tsymbalistyi** [comment]
perlasivakrishna, you should be able to implement decent solution using existing dlls. It is hard for me to understand your problem though. Can you post some code snippet so we could see how you create a channel?
Something like this should work:
```c#
pushBroker.RegisterAppleService(new ApplePushChannelSettings(true, appleCertificate, password, true));
```
First argument means production certificate type.
Last one disables certificate check (it is enabled by default).

**Comment by perlasivakrishna** [comment]
@v-tsymbalistyi , Thank you  so much, 
pushBroker.RegisterAppleService(new ApplePushChannelSettings(true, appleCertificate, password, true));
After this change every thing is working fine, Previously we are trying to edit in the class(ApplePushChannelSettings where There is a defined constructor with value False). 

Thanks..
