### ISSUE TITLE
Dev 3.0 issue

### ISSUE THREAD

**Issue by jjxtra** [Redth/PushSharp#594]
I get this error: Your Certificate is not in the new combined Sandbox/Production APNS certificate format, please create a new single certificate to use

I can find nothing in the code or on the Internet that explains how to create this new single format certificate.

**Comment by Redth** [comment]
This was fixed in c95a86d9592d7693a89c4260c0324f44ccd061fe and should be available in the 3.0.x nuget prerelease packages.

In your member center on apple's site you can create a new one by going to *Certificates* -> *Add New*  and picking *Apple Push Notification service SSL (Sandbox & Production)*

![image](https://cloud.githubusercontent.com/assets/271950/12237081/ee623c9c-b84a-11e5-85dd-1cf131ef18ee.png)

**Comment by jjxtra** [comment]
Thanks.
