### ISSUE TITLE
ios "invalid token"

### ISSUE THREAD

**Issue by jhaoheng** [Redth/PushSharp#612]
hello

I have two P12 file (development and production)
Use pushsharp with "development p12" is ok.
But when i use "production p12" file to send notification, i got an exception "invalid token"
Just only one token , and why got "invalid token" when use "production p12"?
I create PHP and Python send to APNS is ok.(both development and production pem file)
and PushSharp can't pass "Production p12". and the error always "invalid token"

Does anyone know it??
Thx so much.

**Comment by Redth** [comment]
If your device token was generated by your app that was compiled with a Development provisioning profile, it can only be used on the APNS sandbox servers.  If your device token was generated by your app that was compiled with an AdHoc or AppStore provisioning profile it can only be used on the APNS Production servers.  Otherwise you will get an invalid token error.

**Comment by jhaoheng** [comment]
hello Redth

May i mark this code section, let code don't do this judge?
and Could you help me , where to find this section?
Because i mark "exception 8" code in
```
AppleNotification.cs
- public byte[] ToBytes()
``` 
But this problem still occurs.
and i set break point to check exception
can't find where the code  judge this exception.

thank you so much

**Comment by Redth** [comment]
From what I can tell this isn't a problem with PushSharp, but rather trying to use a device token from a Development provisioned app in the Production server (or the opposite).  

I don't really understand what you are asking beyond this.

**Comment by jhaoheng** [comment]
So... you mean PushSharp check token and provision is auto response by system?
PushSharp is get system response , and show exception to developer?

Thanks
